/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GetFarCars.Com.Admin;

import Dashboard.*;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import com.carrentalsystem.system.DBConnector;
import com.getfarcar.common.User;
import com.getfarcar.common.UserImp;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KA VI YA
 */
public class AdminUserManage extends javax.swing.JFrame {
    PreparedStatement pst1;
    DBConnector obj=DBConnector.getObject();
    java.sql.Connection conn=DBConnector.getConnection();
    CardLayout cardLayout1;
    String UserID;

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }
    CardLayout cardLayout;
    public AdminUserManage() {
        
        initComponents();
        Load();
        cardLayout =(CardLayout)(jPanel1.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        priCard2 = new javax.swing.JPanel();
        priCard4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        txtLName1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtRegNo1 = new javax.swing.JTextField();
        txtCity1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        selStatus1 = new javax.swing.JComboBox<String>();
        jLabel27 = new javax.swing.JLabel();
        selGender1 = new javax.swing.JComboBox<String>();
        jLabel28 = new javax.swing.JLabel();
        txtFName1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtDOB1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        LecAdd = new rojerusan.RSMaterialButtonRectangle();
        LecDelete = new rojerusan.RSMaterialButtonRectangle();
        LecUpdate = new rojerusan.RSMaterialButtonRectangle();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        StCPwd1 = new javax.swing.JPasswordField();
        StPwd1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Jdriver = new rojeru_san.complementos.RSTableMetro();
        priCard1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRegNo = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cusGender = new javax.swing.JComboBox<String>();
        jLabel15 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Csearch = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane2 = new javax.swing.JScrollPane();
        cusTable = new rojeru_san.complementos.RSTableMetro();
        StDelete = new rojerusan.RSMaterialButtonRectangle();
        StUpdate = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        StCPwd = new javax.swing.JPasswordField();
        StPwd = new javax.swing.JPasswordField();
        ShowPassword = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        StAdd1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel14 = new javax.swing.JLabel();
        txtAddressl2 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        priCard2.setBackground(new java.awt.Color(255, 255, 255));

        priCard4.setBackground(new java.awt.Color(255, 255, 255));
        priCard4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Last Name");
        priCard4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 133, -1, 32));
        priCard4.add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 253, 398, 32));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Lecturer ID");
        priCard4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 97, 90, 29));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("First Name");
        priCard4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 133, -1, 32));
        priCard4.add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 193, 29));
        priCard4.add(txtLName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 174, 192, 29));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Adress Line 2");
        priCard4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 291, -1, 32));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Adress Line 1");
        priCard4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 214, -1, 32));
        priCard4.add(txtRegNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 95, 310, 32));
        priCard4.add(txtCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 330, 398, 32));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Gender");
        priCard4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 95, -1, 32));

        selStatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senior professor", "Professor", "Dean", "HOD" }));
        priCard4.add(selStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 206, 186, 28));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Position");
        priCard4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 171, -1, 32));

        selGender1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        priCard4.add(selGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 136, 186, 28));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Phone Number");
        priCard4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, 32));
        priCard4.add(txtFName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 174, 176, 29));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Date of Birth");
        priCard4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 32));
        priCard4.add(txtDOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 176, 29));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Re-enter the password");
        priCard4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 329, -1, 32));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("Password");
        priCard4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 252, -1, 32));

        LecAdd.setText("Add");
        LecAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecAddActionPerformed(evt);
            }
        });
        priCard4.add(LecAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 90, 40));

        LecDelete.setText("Delete");
        LecDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecDeleteActionPerformed(evt);
            }
        });
        priCard4.add(LecDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 107, 40));

        LecUpdate.setText("Update");
        LecUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecUpdateActionPerformed(evt);
            }
        });
        priCard4.add(LecUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 107, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("Once Set the password Cann't Modifiey");

        StCPwd1.setText("jPassw");

        StPwd1.setText("jPas1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StCPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGap(37, 37, 37)
                .addComponent(StPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(StCPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        priCard4.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 220, 180));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("User Management >Driver->");
        priCard4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 41));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel45.setText("jLabel18");
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        priCard4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel46.setText("jLabel29");
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        priCard4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 20, -1));

        Jdriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "F Name", "L Name", "Address ", "City", "Email", "NIC", "Contact"
            }
        ));
        Jdriver.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        Jdriver.setColorFilasForeground1(new java.awt.Color(204, 51, 0));
        Jdriver.setColorFilasForeground2(new java.awt.Color(255, 0, 0));
        Jdriver.setFuenteFilas(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jdriver.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jdriver.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jdriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JdriverMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(Jdriver);
        if (Jdriver.getColumnModel().getColumnCount() > 0) {
            Jdriver.getColumnModel().getColumn(0).setPreferredWidth(40);
            Jdriver.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        priCard4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 670, 140));

        javax.swing.GroupLayout priCard2Layout = new javax.swing.GroupLayout(priCard2);
        priCard2.setLayout(priCard2Layout);
        priCard2Layout.setHorizontalGroup(
            priCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(priCard4, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        priCard2Layout.setVerticalGroup(
            priCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priCard2Layout.createSequentialGroup()
                .addComponent(priCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(priCard2, "priCard2");

        priCard1.setBackground(new java.awt.Color(255, 255, 255));
        priCard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Last Name");
        priCard1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 32));
        priCard1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 253, 398, 32));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Registration Number");
        priCard1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 143, 29));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("First Name");
        priCard1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 32));
        priCard1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 193, 29));
        priCard1.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 192, 29));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("City");
        priCard1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 32));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Adress Line 1");
        priCard1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 214, -1, 32));
        priCard1.add(txtRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 240, 32));
        priCard1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, 32));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Gender");
        priCard1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 95, -1, 32));

        cusGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        priCard1.add(cusGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 136, 186, 28));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Phone Number");
        priCard1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, 32));
        priCard1.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 176, 29));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("NIC ");
        priCard1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 32));
        priCard1.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 176, 29));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Password");
        priCard1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 252, -1, 32));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Re-enter the password");
        priCard1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 329, -1, 32));

        Csearch.setText("Search");
        Csearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsearchActionPerformed(evt);
            }
        });
        priCard1.add(Csearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 90, 40));

        cusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "F Name", "L Name", "Address ", "City", "Email", "NIC", "Contact"
            }
        ));
        cusTable.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        cusTable.setColorFilasForeground1(new java.awt.Color(204, 51, 0));
        cusTable.setColorFilasForeground2(new java.awt.Color(255, 0, 0));
        cusTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cusTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cusTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cusTable);
        if (cusTable.getColumnModel().getColumnCount() > 0) {
            cusTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            cusTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        priCard1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 670, 110));

        StDelete.setText("Delete");
        StDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StDeleteActionPerformed(evt);
            }
        });
        priCard1.add(StDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 107, 40));

        StUpdate.setText("Update");
        StUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StUpdateActionPerformed(evt);
            }
        });
        priCard1.add(StUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 107, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Once Set the password Cann't Modifiey");

        StCPwd.setText("jPassw");

        StPwd.setText("jPas1");

        ShowPassword.setText(" Show Password");
        ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowPassword)
                    .addComponent(StCPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(37, 37, 37)
                .addComponent(StPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(StCPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPassword)
                .addContainerGap())
        );

        priCard1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 220, 180));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel36.setText("jLabel29");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        priCard1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 20, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel44.setText("jLabel18");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        priCard1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        StAdd1.setText("Add");
        StAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StAdd1ActionPerformed(evt);
            }
        });
        priCard1.add(StAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 90, 40));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Adress Line 2");
        priCard1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 291, -1, 32));
        priCard1.add(txtAddressl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 330, 180, 32));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel49.setText("Email");
        priCard1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 143, 29));
        priCard1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 240, 32));

        jLabel50.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel50.setText("User Management >Customer->");
        priCard1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 41));

        jPanel1.add(priCard1, "priCard1");

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 690, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/get.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/home.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 30, 40));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(153, 0, 0));
        rSMaterialButtonRectangle2.setText("MANAGE DRIVERS");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 50));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(153, 0, 0));
        rSMaterialButtonRectangle4.setText("MANAGE CUSTOMER");
        rSMaterialButtonRectangle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/Update1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 100));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Management");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        
PreparedStatement insert;
private void Load(){
 
        DefaultTableModel UFT=(DefaultTableModel) cusTable.getModel();
        UFT.setRowCount(0);
        UserImp userImp = new UserImp();
        List<User> cuslist=userImp.list("customer");
        for(User cus:cuslist){
            UFT.addRow(new Object[]{cus.getID(),cus.getfName(),cus.getlName(),cus.getAddressl1()+cus.getAddressl2(),cus.getCity(),cus.getEmail(),cus.getNIC(),cus.getContactno()});
        }
        
        DefaultTableModel UD=(DefaultTableModel) Jdriver.getModel();
        UD.setRowCount(0);
        List<User> drlist=userImp.list("driver");
        for(User drv:drlist){
            UD.addRow(new Object[]{drv.getID(),drv.getfName(),drv.getlName(),drv.getAddressl1()+drv.getAddressl2(),drv.getCity(),drv.getEmail(),drv.getNIC(),drv.getContactno()});
        }
        
        /*List<User> sellerlist=sellerImp.list("Seller");
        for(User sel:sellerlist){      
           SellerName.addItem(sel.getSellerName());
           UFT.addRow(new Object[]{sel.getSellerID(),sel.getSellerName(),sel.getSellerAddress(),sel.getContacatNo()});
        }*/
        /*
         List<User> Cashlist=sellerImp.list("Cheshire");
        for(User ch:Cashlist){
            UFT.addRow(new Object[]{ch.getSellerID(),ch.getSellerName(),ch.getSellerAddress(),ch.getContacatNo()});
        }
        
        List<User> UserRolle=sellerImp.Userlist();
        for(User usr:UserRolle){
            UserType.addItem(usr.getUserType());
        
        }
        
        ProductImp pImp = new ProductImp();
        List<Category> productlist=pImp.Plist();
        for(Category cat:productlist){
            PCategory.addItem(cat.getCategoryName());
        
        }
        
        ProductImp productImp = new ProductImp();
        List<Product> list1=productImp.list();
        DefaultTableModel PDFT=(DefaultTableModel) PTable.getModel();
        PDFT.setRowCount(0);
        for(Product pt:list1){
            PDFT.addRow(new Object[]{pt.getProductID(),pt.getProductName(),pt.getQuantity(),pt.getPrice(),pt.getProductCategoryID()});
        }*/

}


    private void rSMaterialButtonRectangle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle4ActionPerformed
       cardLayout.show(jPanel1,"priCard1");

    }//GEN-LAST:event_rSMaterialButtonRectangle4ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        cardLayout.show(jPanel1,"priCard2");
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void cusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusTableMouseClicked
           
            DefaultTableModel df=(DefaultTableModel)cusTable.getModel();
            int selectedIndex=cusTable.getSelectedRow();
            txtRegNo.setText(df.getValueAt(selectedIndex, 0).toString());
            txtFName.setText(df.getValueAt(selectedIndex, 1).toString());
            txtLName.setText(df.getValueAt(selectedIndex, 2).toString());
            txtAddress.setText(df.getValueAt(selectedIndex, 3).toString());
            txtCity.setText(df.getValueAt(selectedIndex, 4).toString());

            String gen = (String)df.getValueAt(selectedIndex, 5).toString();
            //selGender.addItem(gen);
            cusGender.setSelectedItem(gen);

            txtDOB.setText(df.getValueAt(selectedIndex, 6).toString());
            txtPhone.setText(df.getValueAt(selectedIndex, 7).toString()); 
    }//GEN-LAST:event_cusTableMouseClicked

    private void CsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsearchActionPerformed
            
        String UID=(JOptionPane.showInputDialog("Enter the category ID"));
        UserImp userImp = new UserImp();
        User user = new User();     
        user=userImp.Serch(UID);
        
        txtRegNo.setText(user.getID());
        txtFName.setText(user.getfName());
        txtEmail.setText(user.getEmail());
        txtLName.setText(user.getlName());
        txtAddress.setText(user.getAddressl1());
        txtAddressl2.setText(user.getAddressl2());
        txtCity.setText(user.getCity());
        txtDOB.setText(user.getNIC());
        cusGender.setSelectedItem(user.getGender());
        txtPhone.setText(String.valueOf(user.getContactno()));
        txtRegNo.requestFocus();
;
        
    }//GEN-LAST:event_CsearchActionPerformed

    private void StUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StUpdateActionPerformed
        User user = new User();
        user.setID(txtRegNo.getText());
        user.setfName(txtFName.getText());
        user.setlName(txtLName.getText());
        user.setAddressl1(txtAddress.getText());
        user.setAddressl2(txtAddressl2.getText());
        user.setCity(txtCity.getText());
        user.setNIC(txtDOB.getText());
        user.setEmail(txtEmail.getText());
        user.setContactno(Integer.parseInt(txtPhone.getText()));
        user.setGender((String)cusGender.getSelectedItem());
        
        UserImp userImp = new UserImp();
        userImp.Update(user,"customer");
        Load();
    }//GEN-LAST:event_StUpdateActionPerformed

    private void StDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StDeleteActionPerformed
            User user = new User();
            user.setID(txtRegNo.getText());
            UserImp userImp = new UserImp();
            userImp.Delete(user,"customer");

            Load();

            txtRegNo.setText("");
            txtFName.setText("");
            txtLName.setText("");
            txtAddress.setText(""); 
            txtCity.setText("");
            txtDOB.setText("");
            txtPhone.setText("");
            txtRegNo.requestFocus();
            

       
    }//GEN-LAST:event_StDeleteActionPerformed


    private void LecAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecAddActionPerformed
            String RegNO=txtRegNo1.getText();
            String FName=txtFName1.getText();
            String LName=txtLName1.getText();
            String Address=txtAddress1.getText();
            String City=txtCity1.getText();
            String Gender=(String)selGender1.getSelectedItem();
            String DOB=txtDOB1.getText();
            String Telephone=txtPhone1.getText();
            String Position=(String)selStatus1.getSelectedItem();
            String Password=StPwd1.getText();
            String CPassword=StCPwd1.getText();
   

            try {

            insert=conn1.prepareStatement("insert into lectures(lec_id,f_name,l_name,address_l1,address_l2,gender,dob,phone_num,position) values (?,?,?,?,?,?,?,?,?)");
            insert.setString(1, RegNO);
            insert.setString(2, FName);
            insert.setString(3, LName);
            insert.setString(4,Address );
            insert.setString(5, City);
            insert.setString(6, Gender);
            insert.setString(7, DOB);
            insert.setString(8,Telephone );
            insert.setString(9,Position );

            if(Password.equals(CPassword)){

                insert.executeUpdate();

                insert=conn1.prepareStatement("insert into log_user(Uname,Password,Role) values (?,?,2)");
                insert.setString(1, RegNO);
                insert.setString(2, Password);
                insert.executeUpdate();

                JOptionPane.showMessageDialog(this,"Lecturer is Added!!");
                lec_table_update();

                txtRegNo1.setText("");
                txtFName1.setText("");
                txtLName1.setText("");
                txtAddress1.setText(""); 
                txtCity1.setText("");
                txtDOB1.setText("");
                txtPhone1.setText("");
                txtRegNo1.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this,"Password not matched!!");
                StPwd1.setText("");
                StCPwd1.setText("");
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(AdminUserManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LecAddActionPerformed

    private void LecDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecDeleteActionPerformed
       
        DefaultTableModel df=(DefaultTableModel)Jdriver.getModel();
        int selectedIndex=Jdriver.getSelectedRow();
    try {
        String index_num=df.getValueAt(selectedIndex,0).toString();
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Delete the Recode", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
             Connection conn1=ConnectDB.MyDBConnection();

            insert=conn1.prepareStatement("delete from lectures where lec_id=?");
            insert.setString(1,index_num );
            insert.executeUpdate();

            insert=conn1.prepareStatement("delete from log_user where Uname=?");
            insert.setString(1,index_num );
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this,"Recode Deleted!!");
            lec_table_update();

            txtRegNo1.setText("");
            txtFName1.setText("");
            txtLName1.setText("");
            txtAddress1.setText(""); 
            txtCity1.setText("");
            txtDOB1.setText("");
            txtPhone1.setText("");
            txtRegNo1.requestFocus();
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminUserManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LecDeleteActionPerformed

    private void LecUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecUpdateActionPerformed
        DefaultTableModel df=(DefaultTableModel)Jdriver.getModel();
        int selectedIndex=Jdriver.getSelectedRow();
        try {
 

            String RegNO=txtRegNo1.getText();
            String FName=txtFName1.getText();
            String LName=txtLName1.getText();
            String Address=txtAddress1.getText();
            String City=txtCity1.getText();
            String Gender=(String)selGender1.getSelectedItem();
            String DOB=txtDOB1.getText();
            String Telephone=txtPhone1.getText();
            String Position=(String)selStatus1.getSelectedItem();


            Connection conn1=ConnectDB.MyDBConnection();
            insert=conn1.prepareStatement("update  lectures set lec_id=?,f_name=?,l_name=?,address_l1=?,address_l2=?,gender=?,dob=?,phone_num=?,position=? where lec_id=?");
            insert.setString(1, RegNO);
            insert.setString(2, FName);
            insert.setString(3, LName);
            insert.setString(4,Address );
            insert.setString(5, City);
            insert.setString(6, Gender);
            insert.setString(7, DOB);
            insert.setString(8,Telephone );
            insert.setString(9,Position );
            insert.setString(10, RegNO);


            insert.executeUpdate();

            JOptionPane.showMessageDialog(this,"Recode Update!!");
            lec_table_update();

            txtRegNo1.setText("");
            txtFName1.setText("");
            txtLName1.setText("");
            txtAddress1.setText(""); 
            txtCity1.setText("");
            txtDOB1.setText("");
            txtPhone1.setText("");
            txtRegNo1.requestFocus();


        } catch (SQLException ex) {
            Logger.getLogger(AdminUserManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LecUpdateActionPerformed



    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Admindashboard add=new Admindashboard();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Admindashboard add=new Admindashboard();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){    
                System.exit(0);
        }
    }//GEN-LAST:event_jLabel44MouseClicked

    private void ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordMouseClicked
        if(ShowPassword.isSelected()){
            StPwd.setEchoChar((char)0);
            StCPwd.setEchoChar((char)0);
            ShowPassword.setText("Hide Password");
        }
        else{
            StPwd.setEchoChar('•');
            StCPwd.setEchoChar('•');
            ShowPassword.setText("Show Password");
        }
    }//GEN-LAST:event_ShowPasswordMouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){    
                System.exit(0);
        }
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel46MouseClicked

    private void JdriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JdriverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JdriverMouseClicked

    private void StAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StAdd1ActionPerformed
        
        User user = new User();
        user.setID(txtRegNo.getText());
        user.setfName(txtFName.getText());
        user.setlName(txtLName.getText());
        user.setAddressl1(txtAddress.getText());
        user.setAddressl2(txtAddressl2.getText());
        user.setCity(txtCity.getText());
        user.setNIC(txtDOB.getText());
        user.setEmail(txtEmail.getText());
        user.setContactno(Integer.parseInt(txtPhone.getText()));
        user.setGender((String)cusGender.getSelectedItem());
        
        UserImp userImp = new UserImp();
        userImp.Add(user,"customer");
        Load();
        
        
  
    }//GEN-LAST:event_StAdd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUserManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle Csearch;
    private rojeru_san.complementos.RSTableMetro Jdriver;
    private rojerusan.RSMaterialButtonRectangle LecAdd;
    private rojerusan.RSMaterialButtonRectangle LecDelete;
    private rojerusan.RSMaterialButtonRectangle LecUpdate;
    private javax.swing.JCheckBox ShowPassword;
    private rojerusan.RSMaterialButtonRectangle StAdd1;
    private javax.swing.JPasswordField StCPwd;
    private javax.swing.JPasswordField StCPwd1;
    private rojerusan.RSMaterialButtonRectangle StDelete;
    private javax.swing.JPasswordField StPwd;
    private javax.swing.JPasswordField StPwd1;
    private rojerusan.RSMaterialButtonRectangle StUpdate;
    private javax.swing.JComboBox<String> cusGender;
    private rojeru_san.complementos.RSTableMetro cusTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel priCard1;
    private javax.swing.JPanel priCard2;
    private javax.swing.JPanel priCard4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private javax.swing.JComboBox<String> selGender1;
    private javax.swing.JComboBox<String> selStatus1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddressl2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDOB1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFName1;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtLName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtRegNo;
    private javax.swing.JTextField txtRegNo1;
    // End of variables declaration//GEN-END:variables
}
